spring.application.name=TripPhoto

# JPA
spring.jpa.open-in-view=false

# GraphQL
spring.graphql.graphiql.enabled=true

# Actuator (Nginx?? /actuator/* ?? ?)
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never