-- Refresh tokens are stored only as SHA-256 hashes and rotated on every use.
CREATE TABLE refresh_token (
    id                 NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_user_id    NUMBER(19)     NOT NULL,
    token_hash         CHAR(64)       NOT NULL,
    expires_at         TIMESTAMP      NOT NULL,
    created_at         TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_refresh_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_refresh_token_user FOREIGN KEY (service_user_id) REFERENCES service_user (id)
);

CREATE INDEX idx_refresh_token_user ON refresh_token (service_user_id);
