-- V4: "팟 공유 여행 + 멤버별 기록" 구조로 전환
--   * trip        = 팟의 한 번의 방문 (지역 + 기간 + 키워드) — 팟 전체가 공유한다
--   * trip_record = 그 방문에 대한 멤버별 기록 (코멘트 + 사진) — 신설
--   * trip_image가 trip이 아니라 trip_record에 매달린다 → "누가 올린 사진인지"가 표현된다
--   * trip.color 제거, trip.keyword 도입 (기록하기 플로우의 키워드 선택이 색상 선택을 대체)
--   * party_member.created_at 추가 — 여행 기록 아코디언의 팟원 정렬(가입 순서)에 필요
-- Oracle(ATP)과 H2(MODE=Oracle) 양쪽에서 동일하게 동작해야 한다.

CREATE TABLE trip_record (
    id                 NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id            NUMBER(19)     NOT NULL,
    service_user_id    NUMBER(19)     NOT NULL,
    -- COMMENT는 Oracle 예약어라 컬럼명을 comment_text로 둔다
    comment_text       VARCHAR2(500),
    created_at         TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at         TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_trip_record UNIQUE (trip_id, service_user_id),
    CONSTRAINT fk_trip_record_trip FOREIGN KEY (trip_id) REFERENCES trip (id),
    CONSTRAINT fk_trip_record_user FOREIGN KEY (service_user_id) REFERENCES service_user (id)
);

-- trip_id 조회는 uq_trip_record(trip_id, service_user_id)가 커버하므로 별도 인덱스 불필요
CREATE INDEX idx_trip_record_user ON trip_record (service_user_id);

-- 기존 여행 1건 = 등록자 1명의 기록으로 이관
INSERT INTO trip_record (trip_id, service_user_id)
SELECT id, created_by FROM trip WHERE created_by IS NOT NULL;

ALTER TABLE trip_image ADD trip_record_id NUMBER(19);

UPDATE trip_image ti
SET trip_record_id = (SELECT tr.id FROM trip_record tr WHERE tr.trip_id = ti.trip_id);

-- 등록자가 없는(탈퇴) 여행의 사진은 귀속시킬 기록이 없다
DELETE FROM trip_image WHERE trip_record_id IS NULL;

ALTER TABLE trip_image DROP CONSTRAINT fk_trip_image_trip;
ALTER TABLE trip_image DROP CONSTRAINT uq_trip_image;
ALTER TABLE trip_image DROP COLUMN trip_id;
ALTER TABLE trip_image MODIFY trip_record_id NOT NULL;
ALTER TABLE trip_image ADD CONSTRAINT uq_trip_image UNIQUE (trip_record_id, image_id);
ALTER TABLE trip_image ADD CONSTRAINT fk_trip_image_record
    FOREIGN KEY (trip_record_id) REFERENCES trip_record (id);

-- 색상 → 키워드. 기존 행은 값을 알 수 없으므로 첫 번째 키워드로 백필한다.
ALTER TABLE trip ADD keyword VARCHAR2(20);
UPDATE trip SET keyword = 'HEALING' WHERE keyword IS NULL;
ALTER TABLE trip MODIFY keyword NOT NULL;
ALTER TABLE trip DROP COLUMN color;

-- 팟원 가입 순서. 기존 행은 같은 시각으로 채워지므로 정렬은 (created_at, id)로 한다.
ALTER TABLE party_member ADD created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;
