-- V6: 현재 도메인 모델대로 스키마 재구축 (V5에서 전부 드롭한 뒤)
--   * V1~V4의 최종 상태 + 프로필 이미지 프리셋 전환을 한 번에 반영한다.
--   * service_user.profile_image_url(자유 URL) → profile_image(프리셋 번호, 1부터)
--   * trip은 팟의 한 번의 방문(지역 + 기간 + 키워드), trip_record는 그 방문의 멤버별 기록,
--     trip_image는 trip이 아니라 trip_record에 매달린다.
--   * FK 제약은 두지 않는다 — 참조 무결성은 애플리케이션 레이어에서 보장한다.
--     대신 조인/조회 경로를 받쳐주는 인덱스는 그대로 유지한다.
--   * region은 프론트 지도(GeoJSON)와 코드를 맞춰 시딩까지 함께 한다.
-- Oracle(ATP)과 H2(MODE=Oracle) 양쪽에서 동일하게 동작해야 한다.
--   → INSERT ALL / SELECT ... FROM DUAL 같은 Oracle 전용 문법은 쓰지 않는다.

CREATE TABLE service_user (
    id                 NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nickname           VARCHAR2(40)   NOT NULL,
    -- 서버가 정의한 프리셋 아바타 번호. 기본값 1.
    profile_image      NUMBER(2)      DEFAULT 1 NOT NULL,
    created_at         TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at         TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 자연키(행정구역 코드) 테이블.
-- region_code는 CHAR가 아니라 VARCHAR2다 — CHAR(5)는 공백 패딩이라 광역시 코드 '11'이
-- '11   '로 저장돼 GeoJSON properties.code('11')와 비교가 어긋난다.
CREATE TABLE region (
    region_code        VARCHAR2(5)    PRIMARY KEY,
    region_name        VARCHAR2(50)   NOT NULL,  -- 정식 행정구역명 (예: 서울특별시)
    display_name       VARCHAR2(50)   NOT NULL,  -- 지도/UI 표시명 (예: 서울)
    region_level       VARCHAR2(10)   NOT NULL,  -- metro | city | county
    base_year          CHAR(4)        NOT NULL,  -- 행정구역 경계 기준연도
    name_eng           VARCHAR2(60),             -- 영문명 (원본 미제공 시 NULL)
    geo_source         VARCHAR2(50)   NOT NULL,  -- 원본 GeoJSON 소스 식별자
    created_at         TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at         TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_region_level CHECK (region_level IN ('metro', 'city', 'county'))
);

CREATE TABLE social_account (
    id                 NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_user_id    NUMBER(19)     NOT NULL,
    provider           VARCHAR2(20)   NOT NULL,
    provider_user_id   VARCHAR2(150)  NOT NULL,
    provider_email     VARCHAR2(320),
    created_at         TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at         TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_social_account_provider UNIQUE (provider, provider_user_id)
);

CREATE TABLE party (
    id                 NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    party_name         VARCHAR2(100)  NOT NULL,
    invite_code        VARCHAR2(12)   NOT NULL,
    owner_id           NUMBER(19)     NOT NULL,
    created_at         TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at         TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_party_invite_code UNIQUE (invite_code)
);

CREATE TABLE party_member (
    id                 NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    party_id           NUMBER(19)     NOT NULL,
    service_user_id    NUMBER(19)     NOT NULL,
    -- 여행 기록 아코디언의 팟원 정렬(가입 순서)에 쓴다. 정렬은 (created_at, id)로 한다.
    created_at         TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_party_member UNIQUE (party_id, service_user_id)
);

CREATE TABLE image (
    id                 NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_url       VARCHAR2(512)  NOT NULL,
    thumbnail_url      VARCHAR2(512),
    uploader_id        NUMBER(19),
    -- presigned URL 발급 시점에 확정되는 스토리지 키. 업로드 검증(HEAD)/삭제가 이 키로 동작한다.
    -- 업로드 여부의 source of truth는 스토리지이므로 상태 컬럼은 두지 않는다.
    object_key         VARCHAR2(200)  NOT NULL,
    created_at         TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_image_object_key UNIQUE (object_key)
);

CREATE TABLE trip (
    id                 NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    party_id           NUMBER(19)     NOT NULL,
    -- region.region_code와 타입을 맞춘다 (VARCHAR2, 패딩 없음)
    region_code        VARCHAR2(5)    NOT NULL,
    -- 기록하기 플로우의 키워드 선택이 기존 color를 대체한다.
    keyword            VARCHAR2(20)   NOT NULL,
    start_date         DATE           NOT NULL,
    end_date           DATE           NOT NULL,
    created_by         NUMBER(19),
    created_at         TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at         TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE trip_record (
    id                 NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id            NUMBER(19)     NOT NULL,
    service_user_id    NUMBER(19)     NOT NULL,
    -- COMMENT는 Oracle 예약어라 컬럼명을 comment_text로 둔다
    comment_text       VARCHAR2(500),
    created_at         TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at         TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_trip_record UNIQUE (trip_id, service_user_id)
);

CREATE TABLE trip_image (
    id                 NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_record_id     NUMBER(19)     NOT NULL,
    image_id           NUMBER(19)     NOT NULL,
    image_date         DATE,
    created_at         TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_trip_image UNIQUE (trip_record_id, image_id)
);

-- 참조 컬럼 인덱스. UNIQUE 제약이 선두 컬럼으로 커버하는 경로
-- (trip_record.trip_id, trip_image.trip_record_id, party_member.party_id)는 별도로 만들지 않는다.
CREATE INDEX idx_social_account_user ON social_account (service_user_id);
CREATE INDEX idx_party_owner ON party (owner_id);
CREATE INDEX idx_party_member_member ON party_member (service_user_id);
CREATE INDEX idx_image_uploader ON image (uploader_id);
CREATE INDEX idx_trip_party ON trip (party_id);
CREATE INDEX idx_trip_region ON trip (region_code);
CREATE INDEX idx_trip_creator ON trip (created_by);
CREATE INDEX idx_trip_record_user ON trip_record (service_user_id);
CREATE INDEX idx_trip_image_image ON trip_image (image_id);

-- =====================================================================
-- region 시딩 (168건)
--   출처: southkorea/southkorea-maps kostat 2018
--     - skorea-provinces-2018-topo-simple.json      (metro 8)
--     - skorea-municipalities-2018-topo-simple.json (city 78 / county 82)
--   프론트 src/shared/lib/loadKoreaGeoJson.ts가 렌더하는 지역과 1:1로 맞춘다.
--   '-merged-gu' 소스는 자치구가 있는 시(수원/성남/…)를 시 단위로 합친 것이라
--   원본에 영문명이 없어 name_eng가 NULL이다.
--   created_at/updated_at은 컬럼 DEFAULT로 채운다 (SYSTIMESTAMP는 Oracle 전용).
-- =====================================================================

INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('11', '서울특별시', '서울', 'metro', '2018', 'Seoul', 'skorea-provinces-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('21', '부산광역시', '부산', 'metro', '2018', 'Busan', 'skorea-provinces-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('21310', '기장군', '기장', 'county', '2018', 'Gijang-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('22', '대구광역시', '대구', 'metro', '2018', 'Daegu', 'skorea-provinces-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('22310', '달성군', '달성', 'county', '2018', 'Dalseong-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('23', '인천광역시', '인천', 'metro', '2018', 'Incheon', 'skorea-provinces-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('23310', '강화군', '강화', 'county', '2018', 'Ganghwa-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('23320', '옹진군', '옹진', 'county', '2018', 'Ongjin-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('24', '광주광역시', '광주', 'metro', '2018', 'Gwangju', 'skorea-provinces-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('25', '대전광역시', '대전', 'metro', '2018', 'Daejeon', 'skorea-provinces-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('26', '울산광역시', '울산', 'metro', '2018', 'Ulsan', 'skorea-provinces-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('26310', '울주군', '울주', 'county', '2018', 'Ulju-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('29', '세종특별자치시', '세종', 'metro', '2018', 'Sejongsi', 'skorea-provinces-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('29010', '세종시', '세종', 'city', '2018', 'Sejongsi', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('31010', '수원시', '수원', 'city', '2018', NULL, 'skorea-municipalities-2018-merged-gu');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('31020', '성남시', '성남', 'city', '2018', NULL, 'skorea-municipalities-2018-merged-gu');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('31030', '의정부시', '의정부', 'city', '2018', 'Uijeongbu-si', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('31040', '안양시', '안양', 'city', '2018', NULL, 'skorea-municipalities-2018-merged-gu');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('31050', '부천시', '부천', 'city', '2018', 'Bucheon-si', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('31060', '광명시', '광명', 'city', '2018', 'Gwangmyeong-si', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('31070', '평택시', '평택', 'city', '2018', 'Pyeongtaek-si', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('31080', '동두천시', '동두천', 'city', '2018', 'Dongducheon-si', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('31090', '안산시', '안산', 'city', '2018', NULL, 'skorea-municipalities-2018-merged-gu');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('31100', '고양시', '고양', 'city', '2018', NULL, 'skorea-municipalities-2018-merged-gu');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('31110', '과천시', '과천', 'city', '2018', 'Gwacheon-si', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('31120', '구리시', '구리', 'city', '2018', 'Guri-si', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('31130', '남양주시', '남양주', 'city', '2018', 'Namyangju-si', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('31140', '오산시', '오산', 'city', '2018', 'Osan-si', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('31150', '시흥시', '시흥', 'city', '2018', 'Siheung-si', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('31160', '군포시', '군포', 'city', '2018', 'Gunpo-si', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('31170', '의왕시', '의왕', 'city', '2018', 'Uiwang-si', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('31180', '하남시', '하남', 'city', '2018', 'Hanam-si', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('31190', '용인시', '용인', 'city', '2018', NULL, 'skorea-municipalities-2018-merged-gu');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('31200', '파주시', '파주', 'city', '2018', 'Paju-si', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('31210', '이천시', '이천', 'city', '2018', 'Icheon-si', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('31220', '안성시', '안성', 'city', '2018', 'Anseong-si', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('31230', '김포시', '김포', 'city', '2018', 'Gimpo-si', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('31240', '화성시', '화성', 'city', '2018', 'Hwaseongsi', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('31250', '광주시', '광주', 'city', '2018', 'Gwangju', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('31260', '양주시', '양주', 'city', '2018', 'Yangjusi', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('31270', '포천시', '포천', 'city', '2018', 'Pocheonsi', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('31280', '여주시', '여주', 'city', '2018', 'Yeoju-si', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('31350', '연천군', '연천', 'county', '2018', 'Yeoncheon-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('31370', '가평군', '가평', 'county', '2018', 'Gapyeong-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('31380', '양평군', '양평', 'county', '2018', 'Yangpyeong-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('32010', '춘천시', '춘천', 'city', '2018', 'Chuncheon-si', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('32020', '원주시', '원주', 'city', '2018', 'Wonju-si', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('32030', '강릉시', '강릉', 'city', '2018', 'Gangneung-si', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('32040', '동해시', '동해', 'city', '2018', 'Donghae-si', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('32050', '태백시', '태백', 'city', '2018', 'Taebaek-si', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('32060', '속초시', '속초', 'city', '2018', 'Sokcho-si', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('32070', '삼척시', '삼척', 'city', '2018', 'Samcheok-si', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('32310', '홍천군', '홍천', 'county', '2018', 'Hongcheon-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('32320', '횡성군', '횡성', 'county', '2018', 'Hoengseong-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('32330', '영월군', '영월', 'county', '2018', 'Yeongwol-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('32340', '평창군', '평창', 'county', '2018', 'Pyeongchang-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('32350', '정선군', '정선', 'county', '2018', 'Jeongseon-gun', 'skorea-municipalities-2018');
-- 원본 GeoJSON의 nameEng 오류(Gongju-si)를 그대로 보존한다 — 프론트 키와 어긋나지 않게 하기 위함.
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('32360', '철원군', '철원', 'county', '2018', 'Gongju-si', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('32370', '화천군', '화천', 'county', '2018', 'Hwacheon-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('32380', '양구군', '양구', 'county', '2018', 'Yanggu-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('32390', '인제군', '인제', 'county', '2018', 'Inje-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('32400', '고성군', '고성', 'county', '2018', 'Goseong-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('32410', '양양군', '양양', 'county', '2018', 'Yangyang-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('33020', '충주시', '충주', 'city', '2018', 'Chungju-si', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('33030', '제천시', '제천', 'city', '2018', 'Jecheon-si', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('33040', '청주시', '청주', 'city', '2018', NULL, 'skorea-municipalities-2018-merged-gu');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('33320', '보은군', '보은', 'county', '2018', 'Boeun-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('33330', '옥천군', '옥천', 'county', '2018', 'Okcheon-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('33340', '영동군', '영동', 'county', '2018', 'Yeongdong-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('33350', '진천군', '진천', 'county', '2018', 'Jincheon-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('33360', '괴산군', '괴산', 'county', '2018', 'Goesan-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('33370', '음성군', '음성', 'county', '2018', 'Eumseong-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('33380', '단양군', '단양', 'county', '2018', 'Danyang-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('33390', '증평군', '증평', 'county', '2018', 'Jeungpyeonggun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('34010', '천안시', '천안', 'city', '2018', NULL, 'skorea-municipalities-2018-merged-gu');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('34020', '공주시', '공주', 'city', '2018', 'Gongju-si', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('34030', '보령시', '보령', 'city', '2018', 'Boryeong-si', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('34040', '아산시', '아산', 'city', '2018', 'Asan-si', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('34050', '서산시', '서산', 'city', '2018', 'Seosan-si', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('34060', '논산시', '논산', 'city', '2018', 'Nonsan-si', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('34070', '계룡시', '계룡', 'city', '2018', 'Gyeryongsi', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('34080', '당진시', '당진', 'city', '2018', 'Dangjinsi', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('34310', '금산군', '금산', 'county', '2018', 'Geumsan-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('34330', '부여군', '부여', 'county', '2018', 'Buyeo-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('34340', '서천군', '서천', 'county', '2018', 'Seocheon-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('34350', '청양군', '청양', 'county', '2018', 'Cheongyang-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('34360', '홍성군', '홍성', 'county', '2018', 'Hongseong-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('34370', '예산군', '예산', 'county', '2018', 'Yesan-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('34380', '태안군', '태안', 'county', '2018', 'Taean-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('35010', '전주시', '전주', 'city', '2018', NULL, 'skorea-municipalities-2018-merged-gu');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('35020', '군산시', '군산', 'city', '2018', 'Gunsan-si', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('35030', '익산시', '익산', 'city', '2018', 'Iksan-si', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('35040', '정읍시', '정읍', 'city', '2018', 'Jeongeup-si', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('35050', '남원시', '남원', 'city', '2018', 'Namwon-si', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('35060', '김제시', '김제', 'city', '2018', 'Gimje-si', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('35310', '완주군', '완주', 'county', '2018', 'Wanju-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('35320', '진안군', '진안', 'county', '2018', 'Jinan-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('35330', '무주군', '무주', 'county', '2018', 'Muju-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('35340', '장수군', '장수', 'county', '2018', 'Jangsu-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('35350', '임실군', '임실', 'county', '2018', 'Imsil-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('35360', '순창군', '순창', 'county', '2018', 'Sunchang-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('35370', '고창군', '고창', 'county', '2018', 'Gochang-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('35380', '부안군', '부안', 'county', '2018', 'Buan-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('36010', '목포시', '목포', 'city', '2018', 'Mokpo-si', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('36020', '여수시', '여수', 'city', '2018', 'Yeosu-si', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('36030', '순천시', '순천', 'city', '2018', 'Suncheon-si', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('36040', '나주시', '나주', 'city', '2018', 'Naju-si', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('36060', '광양시', '광양', 'city', '2018', 'Gwangyang-si', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('36310', '담양군', '담양', 'county', '2018', 'Damyang-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('36320', '곡성군', '곡성', 'county', '2018', 'Gokseong-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('36330', '구례군', '구례', 'county', '2018', 'Gurye-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('36350', '고흥군', '고흥', 'county', '2018', 'Goheung-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('36360', '보성군', '보성', 'county', '2018', 'Boseong-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('36370', '화순군', '화순', 'county', '2018', 'Hwasun-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('36380', '장흥군', '장흥', 'county', '2018', 'Jangheung-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('36390', '강진군', '강진', 'county', '2018', 'Gangjin-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('36400', '해남군', '해남', 'county', '2018', 'Haenam-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('36410', '영암군', '영암', 'county', '2018', 'Yeongam-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('36420', '무안군', '무안', 'county', '2018', 'Muan-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('36430', '함평군', '함평', 'county', '2018', 'Hampyeong-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('36440', '영광군', '영광', 'county', '2018', 'Yeonggwang-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('36450', '장성군', '장성', 'county', '2018', 'Jangseong-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('36460', '완도군', '완도', 'county', '2018', 'Wando-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('36470', '진도군', '진도', 'county', '2018', 'Jindo-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('36480', '신안군', '신안', 'county', '2018', 'Sinan-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('37010', '포항시', '포항', 'city', '2018', NULL, 'skorea-municipalities-2018-merged-gu');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('37020', '경주시', '경주', 'city', '2018', 'Gyeongju-si', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('37030', '김천시', '김천', 'city', '2018', 'Gimcheon-si', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('37040', '안동시', '안동', 'city', '2018', 'Andong-si', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('37050', '구미시', '구미', 'city', '2018', 'Gumi-si', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('37060', '영주시', '영주', 'city', '2018', 'Yeongju-si', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('37070', '영천시', '영천', 'city', '2018', 'Yeongcheon-si', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('37080', '상주시', '상주', 'city', '2018', 'Sangju-si', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('37090', '문경시', '문경', 'city', '2018', 'Mungyeong-si', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('37100', '경산시', '경산', 'city', '2018', 'Gyeongsan-si', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('37310', '군위군', '군위', 'county', '2018', 'Gunwi-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('37320', '의성군', '의성', 'county', '2018', 'Uiseong-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('37330', '청송군', '청송', 'county', '2018', 'Cheongsong-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('37340', '영양군', '영양', 'county', '2018', 'Yeongyang-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('37350', '영덕군', '영덕', 'county', '2018', 'Yeongdeok-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('37360', '청도군', '청도', 'county', '2018', 'Cheongdo-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('37370', '고령군', '고령', 'county', '2018', 'Goryeong-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('37380', '성주군', '성주', 'county', '2018', 'Seongju-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('37390', '칠곡군', '칠곡', 'county', '2018', 'Chilgok-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('37400', '예천군', '예천', 'county', '2018', 'Yecheon-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('37410', '봉화군', '봉화', 'county', '2018', 'Bonghwa-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('37420', '울진군', '울진', 'county', '2018', 'Uljin-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('37430', '울릉군', '울릉', 'county', '2018', 'Ulleung-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('38030', '진주시', '진주', 'city', '2018', 'Jinju-si', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('38050', '통영시', '통영', 'city', '2018', 'Tongyeong-si', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('38060', '사천시', '사천', 'city', '2018', 'Sacheon-si', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('38070', '김해시', '김해', 'city', '2018', 'Gimhae-si', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('38080', '밀양시', '밀양', 'city', '2018', 'Miryang-si', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('38090', '거제시', '거제', 'city', '2018', 'Geoje-si', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('38100', '양산시', '양산', 'city', '2018', 'Yangsan-si', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('38110', '창원시', '창원', 'city', '2018', NULL, 'skorea-municipalities-2018-merged-gu');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('38310', '의령군', '의령', 'county', '2018', 'Uiryeong-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('38320', '함안군', '함안', 'county', '2018', 'Haman-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('38330', '창녕군', '창녕', 'county', '2018', 'Changnyeong-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('38340', '고성군', '고성', 'county', '2018', 'Goseong-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('38350', '남해군', '남해', 'county', '2018', 'Namhae-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('38360', '하동군', '하동', 'county', '2018', 'Hadong-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('38370', '산청군', '산청', 'county', '2018', 'Sancheong-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('38380', '함양군', '함양', 'county', '2018', 'Hamyang-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('38390', '거창군', '거창', 'county', '2018', 'Geochang-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('38400', '합천군', '합천', 'county', '2018', 'Hapcheon-gun', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('39010', '제주시', '제주', 'city', '2018', 'Jeju-si', 'skorea-municipalities-2018');
INSERT INTO region (region_code, region_name, display_name, region_level, base_year, name_eng, geo_source) VALUES ('39020', '서귀포시', '서귀포', 'city', '2018', 'Seogwipo-si', 'skorea-municipalities-2018');
