CREATE TABLE service_user (
    id                    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nickname             VARCHAR2(40)    NOT NULL,
    profile_image_url    VARCHAR2(500)   DEFAULT 'DEFAULT' NOT NULL,
    created_at           TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at           TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE social_account (
    id                    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_user_id       NUMBER          NOT NULL,
    provider              VARCHAR2(20)    NOT NULL,
    provider_user_id      VARCHAR2(150)   NOT NULL,
    provider_email        VARCHAR2(320),
    created_at            TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at            TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE party (
    id                    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    party_name            VARCHAR2(100)   NOT NULL,
    invite_code           VARCHAR2(12)    NOT NULL,
    created_at            TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at            TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_party_invite_code UNIQUE (invite_code)
);

CREATE TABLE party_member (
    id                    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    party_id             NUMBER          NOT NULL,
    service_user_id      NUMBER          NOT NULL,
    CONSTRAINT uq_party_member UNIQUE (party_id, service_user_id),
    CONSTRAINT fk_party_member_party FOREIGN KEY (party_id) REFERENCES party(id),
    CONSTRAINT fk_party_member_user FOREIGN KEY (service_user_id) REFERENCES service_user(id)
);

CREATE TABLE regions (
    region_code   CHAR(5)         PRIMARY KEY,
    region_name   VARCHAR2(100)   NOT NULL,
    created_at    TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at    TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE image (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_url  VARCHAR2(512)   NOT NULL,
    thumbnail_url VARCHAR2(512)   NOT NULL,
    uploader_id   NUMBER          NOT NULL,
    created_at    TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_image_uploader FOREIGN KEY (uploader_id) REFERENCES service_user(id)
);

CREATE TABLE trips (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    party_id      NUMBER          NOT NULL,
    region_code   CHAR(5)         NOT NULL,
    color         CHAR(7),
    start_date    DATE            NOT NULL,
    end_date      DATE            NOT NULL,
    created_by    NUMBER          NOT NULL,
    created_at    TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at    TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_trips_party FOREIGN KEY (party_id) REFERENCES party(id),
    CONSTRAINT fk_trips_region FOREIGN KEY (region_code) REFERENCES regions(region_code),
    CONSTRAINT fk_trips_creator FOREIGN KEY (created_by) REFERENCES service_user(id)
);

CREATE TABLE trip_images (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id       NUMBER          NOT NULL,
    image_id      NUMBER          NOT NULL,
    image_date    DATE,
    created_at    TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_trip_images UNIQUE (trip_id, image_id),
    CONSTRAINT fk_trip_images_trip FOREIGN KEY (trip_id) REFERENCES trips(id),
    CONSTRAINT fk_trip_images_image FOREIGN KEY (image_id) REFERENCES image(id)
);

CREATE INDEX idx_social_account_user
    ON social_account (service_user_id);

CREATE INDEX idx_party_member_member
    ON party_member (service_user_id);

CREATE INDEX idx_image_uploader
    ON image (uploader_id);

CREATE INDEX idx_trips_party
    ON trips (party_id);

CREATE INDEX idx_trips_region
    ON trips (region_code);

CREATE INDEX idx_trips_creator
    ON trips (created_by);

CREATE INDEX idx_trip_images_trip
    ON trip_images (trip_id);

CREATE INDEX idx_trip_images_image
    ON trip_images (image_id);