CREATE TABLE service_user (
    id                    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nickname             VARCHAR2(40)    NOT NULL,
    profile_image_url    VARCHAR2(500)   DEFAULT 'DEFAULT' NOT NULL,
    created_at           TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at           TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE social_account (
    id                    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_user_id       NUMBER          NOT NULL,
    provider              VARCHAR2(20)    NOT NULL,
    provider_user_id      VARCHAR2(150)   NOT NULL,
    provider_email        VARCHAR2(320),
    created_at            TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at            TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE party (
    id                    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    party_name            VARCHAR2(100)   NOT NULL,
    invite_code           VARCHAR2(12)    NOT NULL,
    created_at            TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at            TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_party_invite_code UNIQUE (invite_code),
);

CREATE TABLE party_member (
    id                    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    party_id             NUMBER          NOT NULL,
    service_user_id      NUMBER          NOT NULL,
    CONSTRAINT uq_party_member UNIQUE (party_id, service_user_id),
    CONSTRAINT fk_party_member_party FOREIGN KEY (party_id) REFERENCES party(id),
    CONSTRAINT fk_party_member_user FOREIGN KEY (service_user_id) REFERENCES service_user(id)
);

create table image
(
    ID            NUMBER       default "APP_USER"."ISEQ$$_183372".nextval generated as identity primary key,
    ORIGINAL_URL  VARCHAR2(4000) not null,
    THUMBNAIL_URL VARCHAR2(4000) not null,
    CREATED_AT    TIMESTAMP(6) default CURRENT_TIMESTAMP
);

CREATE INDEX idx_social_account_user
    ON social_account (service_user_id);

CREATE INDEX idx_party_member_member
    ON party_member (service_user_id);

