CREATE TABLE service_user (
    id                    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nickname             VARCHAR2(40)    NOT NULL,
    profile_image_url    VARCHAR2(500)   DEFAULT 'DEFAULT' NOT NULL,
    created_at           TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at           TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE social_account (
    id                    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_user_id       NUMBER          NOT NULL,
    provider              VARCHAR2(20)    NOT NULL,
    provider_user_id      VARCHAR2(150)   NOT NULL,
    provider_email        VARCHAR2(320),
    created_at            TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at            TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_social_account_provider_user UNIQUE (provider, provider_user_id),
    CONSTRAINT uq_social_account_user_provider UNIQUE (service_user_id, provider),
    CONSTRAINT fk_social_account_user FOREIGN KEY (service_user_id) REFERENCES service_user(id)
);

CREATE TABLE party (
    id                    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    party_name            VARCHAR2(100)   NOT NULL,
    invite_code           VARCHAR2(12)    NOT NULL,
    owner_user_id         NUMBER          NOT NULL,
    created_at            TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at            TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_party_invite_code UNIQUE (invite_code),
    CONSTRAINT fk_party_owner FOREIGN KEY (owner_user_id) REFERENCES service_user(id)
);

CREATE TABLE party_member (
    id                    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    party_id             NUMBER          NOT NULL,
    service_user_id      NUMBER          NOT NULL,
    CONSTRAINT uq_party_member UNIQUE (party_id, service_user_id),
    CONSTRAINT fk_party_member_party FOREIGN KEY (party_id) REFERENCES party(id),
    CONSTRAINT fk_party_member_user FOREIGN KEY (service_user_id) REFERENCES service_user(id)
);

CREATE TABLE image (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_url  VARCHAR2(512)   NOT NULL,
    thumbnail_url VARCHAR2(512)   NOT NULL,
    uploader_id   NUMBER          NOT NULL,
    taken_lat     DECIMAL(10, 7),
    taken_lng     DECIMAL(10, 7),
    created_at    TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_image_uploader FOREIGN KEY (uploader_id) REFERENCES service_user(id)
);

CREATE TABLE trips (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    party_id      NUMBER          NOT NULL,
    region_code   CHAR(5)         NOT NULL,
    color         CHAR(7),
    start_date    DATE            NOT NULL,
    end_date      DATE            NOT NULL,
    created_by    NUMBER          NOT NULL,
    created_at    TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at    TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_trips_party FOREIGN KEY (party_id) REFERENCES party(id),
    CONSTRAINT fk_trips_creator FOREIGN KEY (created_by) REFERENCES service_user(id)
);

CREATE TABLE trip_photos (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id       NUMBER          NOT NULL,
    image_id      NUMBER          NOT NULL,
    photo_date    DATE,
    created_at    TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_trip_photos UNIQUE (trip_id, image_id),
    CONSTRAINT fk_trip_photos_trip FOREIGN KEY (trip_id) REFERENCES trips(id),
    CONSTRAINT fk_trip_photos_image FOREIGN KEY (image_id) REFERENCES image(id)
);

CREATE INDEX idx_party_owner
    ON party (owner_user_id);

CREATE INDEX idx_social_account_user
    ON social_account (service_user_id);

CREATE INDEX idx_party_member_member
    ON party_member (service_user_id);

CREATE INDEX idx_image_uploader
    ON image (uploader_id);

CREATE INDEX idx_trips_party
    ON trips (party_id);

CREATE INDEX idx_trips_creator
    ON trips (created_by);

CREATE INDEX idx_trip_photos_trip
    ON trip_photos (trip_id);

CREATE INDEX idx_trip_photos_image
    ON trip_photos (image_id);