package udumeoli.tripphoto.common.error

enum class ErrorCode {
    UNAUTHENTICATED,
    FORBIDDEN,
    PARTY_NOT_FOUND,
    TRIP_NOT_FOUND,
    IMAGE_NOT_FOUND,
    REGION_NOT_FOUND,
    MEMBER_NOT_FOUND,
    INVALID_INVITE_CODE,
    IMAGE_NOT_UPLOADED,
    CANNOT_REMOVE_OWNER,
    PARTY_HAS_MEMBERS,
    OWNER_CANNOT_LEAVE,
    RATE_LIMITED,
    VALIDATION_ERROR,
}
